apiVersion: v1
kind: Pod
metadata:
  name: building-app
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-k8s
    imagePullPolicy: IfNotPresent
    image: vrushali28/webapp-k8s:v1
  imagePullSecrets:
  - name: regcred